#!/bin/sh
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
# ln -sf "$PWD/.profile" "$HOME/.bash_profile"
ln -sf "$PWD/scripts" "$HOME/Scripts"
ln -sf "$PWD/nvim" "$HOME/.config/nvim"


for i in vim tmux; do
    cd $i && ./setup
    cd -
done
