#!/usr/bin/env bash

mkdir -p ~/Repos/github.com/docker/docker-install
cd ~/Repos/github.com/docker/
git clone https://github.com/docker/docker-install
cd ~/Repos/github.com/docker/docker-install
./install.sh
dockerd-rootless-setuptool.sh install
